#############################################################################
# Makefile for building: Alarm
# Generated by qmake (2.01a) (Qt 4.7.0) on: lun ago 1 13:41:32 2011
# Project:  Alarm.pro
# Template: app
# Command: /home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/qmake -spec ../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/linux-g++-maemo5 CONFIG+=debug -o Makefile Alarm.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GL_NO_SCISSOR_TEST -DQT_DEFAULT_TEXTURE_GLYPH_CACHE_WIDTH=1024 -DQT_MAEMO5_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/gtk-2.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/freetype2 -DMAEMO_CHANGES -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/gtk-2.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/freetype2 -DMAEMO_CHANGES -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/linux-g++-maemo5 -I. -I../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/include/QtCore -I../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/include/QtGui -I../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/include/QtMaemo5 -I../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/include -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath-link,/usr/lib -Wl,-rpath,/usr/lib
LIBS          = $(SUBLIBS)  -L/home/matias/NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/lib -lalarm -lhildon-time-zone-chooser0 -lclockcore0 -lcityinfo0 -lgq-gconf -ldbus-1 -ldbus-glib-1 -losso -lglib-2.0 -lgobject-2.0 -lgmodule-2.0 -lgdk_pixbuf-2.0 -lpango-1.0 -lcairo -lpangocairo-1.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lfreetype -lfontconfig -lpangoft2-1.0 -lgtk-x11-2.0 -L/usr/lib -lQtMaemo5 -L/usr/X11R6/lib -lQtGui -lQtDBus -lQtXml -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		alarmlist.cpp \
		filedelegate.cpp \
		newalarm.cpp \
		dialog.cpp \
		checkdelegate.cpp \
		valuebutton.cpp \
		dialog2.cpp \
		alarmbutton.cpp \
		maintdelegate.cpp \
		world.cpp \
		dialog3.cpp \
		alsettings.cpp \
		mdialog.cpp \
		tdialog.cpp \
		home.cpp moc_mainwindow.cpp \
		moc_alarmlist.cpp \
		moc_filedelegate.cpp \
		moc_newalarm.cpp \
		moc_dialog.cpp \
		moc_checkdelegate.cpp \
		moc_valuebutton.cpp \
		moc_dialog2.cpp \
		moc_alarmbutton.cpp \
		moc_world.cpp \
		moc_dialog3.cpp \
		moc_alsettings.cpp \
		moc_mdialog.cpp \
		moc_tdialog.cpp \
		moc_home.cpp
OBJECTS       = main.o \
		mainwindow.o \
		alarmlist.o \
		filedelegate.o \
		newalarm.o \
		dialog.o \
		checkdelegate.o \
		valuebutton.o \
		dialog2.o \
		alarmbutton.o \
		maintdelegate.o \
		world.o \
		dialog3.o \
		alsettings.o \
		mdialog.o \
		tdialog.o \
		home.o \
		moc_mainwindow.o \
		moc_alarmlist.o \
		moc_filedelegate.o \
		moc_newalarm.o \
		moc_dialog.o \
		moc_checkdelegate.o \
		moc_valuebutton.o \
		moc_dialog2.o \
		moc_alarmbutton.o \
		moc_world.o \
		moc_dialog3.o \
		moc_alsettings.o \
		moc_mdialog.o \
		moc_tdialog.o \
		moc_home.o
DIST          = ../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/common/unix.conf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/common/linux.conf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/qconfig.pri \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/debug.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/default_post.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/mobility.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/qt.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/moc.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/resources.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/uic.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/yacc.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/lex.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Alarm.pro
QMAKE_TARGET  = Alarm
DESTDIR       = 
TARGET        = Alarm

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_alarmlist.h ui_newalarm.h ui_dialog.h ui_dialog2.h ui_world.h ui_dialog3.h ui_alsettings.h ui_mdialog.h ui_tdialog.h ui_home.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Alarm.pro  ../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/linux-g++-maemo5/qmake.conf ../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/common/unix.conf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/common/linux.conf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/qconfig.pri \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/debug.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/default_post.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/mobility.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/qt.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/moc.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/resources.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/uic.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/yacc.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/lex.prf \
		../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/home/matias/NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/lib/libQtMaemo5.prl \
		/home/matias/NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/lib/libQtGui.prl \
		/home/matias/NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/lib/libQtDBus.prl \
		/home/matias/NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/lib/libQtXml.prl \
		/home/matias/NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/lib/libQtCore.prl
	$(QMAKE) -spec ../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/linux-g++-maemo5 CONFIG+=debug -o Makefile Alarm.pro
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/common/unix.conf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/common/linux.conf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/qconfig.pri:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/qt_functions.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/qt_config.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/default_pre.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/debug.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/default_post.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/mobility.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/warn_on.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/qt.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/unix/thread.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/moc.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/resources.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/uic.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/yacc.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/lex.prf:
../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/home/matias/NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/lib/libQtMaemo5.prl:
/home/matias/NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/lib/libQtGui.prl:
/home/matias/NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/lib/libQtDBus.prl:
/home/matias/NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/lib/libQtXml.prl:
/home/matias/NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../NokiaQtSDK/Maemo/4.6.2/sysroots/fremantle-arm-sysroot-20.2010.36-2-slim/usr/share/qt4/mkspecs/linux-g++-maemo5 CONFIG+=debug -o Makefile Alarm.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Alarm1.0.0 || $(MKDIR) .tmp/Alarm1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Alarm1.0.0/ && $(COPY_FILE) --parents mainwindow.h alarmlist.h filedelegate.h newalarm.h osso-intl.h dialog.h checkdelegate.h valuebutton.h dialog2.h alarmbutton.h maintdelegate.h world.h dialog3.h alsettings.h mdialog.h tdialog.h home.h .tmp/Alarm1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp alarmlist.cpp filedelegate.cpp newalarm.cpp dialog.cpp checkdelegate.cpp valuebutton.cpp dialog2.cpp alarmbutton.cpp maintdelegate.cpp world.cpp dialog3.cpp alsettings.cpp mdialog.cpp tdialog.cpp home.cpp .tmp/Alarm1.0.0/ && $(COPY_FILE) --parents mainwindow.ui alarmlist.ui newalarm.ui dialog.ui dialog2.ui world.ui dialog3.ui alsettings.ui mdialog.ui tdialog.ui home.ui .tmp/Alarm1.0.0/ && (cd `dirname .tmp/Alarm1.0.0` && $(TAR) Alarm1.0.0.tar Alarm1.0.0 && $(COMPRESS) Alarm1.0.0.tar) && $(MOVE) `dirname .tmp/Alarm1.0.0`/Alarm1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Alarm1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_alarmlist.cpp moc_filedelegate.cpp moc_newalarm.cpp moc_dialog.cpp moc_checkdelegate.cpp moc_valuebutton.cpp moc_dialog2.cpp moc_alarmbutton.cpp moc_world.cpp moc_dialog3.cpp moc_alsettings.cpp moc_mdialog.cpp moc_tdialog.cpp moc_home.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_alarmlist.cpp moc_filedelegate.cpp moc_newalarm.cpp moc_dialog.cpp moc_checkdelegate.cpp moc_valuebutton.cpp moc_dialog2.cpp moc_alarmbutton.cpp moc_world.cpp moc_dialog3.cpp moc_alsettings.cpp moc_mdialog.cpp moc_tdialog.cpp moc_home.cpp
moc_mainwindow.cpp: alarmlist.h \
		world.h \
		mainwindow.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_alarmlist.cpp: alarmlist.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) alarmlist.h -o moc_alarmlist.cpp

moc_filedelegate.cpp: filedelegate.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) filedelegate.h -o moc_filedelegate.cpp

moc_newalarm.cpp: newalarm.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) newalarm.h -o moc_newalarm.cpp

moc_dialog.cpp: dialog.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_checkdelegate.cpp: checkdelegate.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) checkdelegate.h -o moc_checkdelegate.cpp

moc_valuebutton.cpp: valuebutton.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) valuebutton.h -o moc_valuebutton.cpp

moc_dialog2.cpp: dialog2.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) dialog2.h -o moc_dialog2.cpp

moc_alarmbutton.cpp: alarmbutton.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) alarmbutton.h -o moc_alarmbutton.cpp

moc_world.cpp: world.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) world.h -o moc_world.cpp

moc_dialog3.cpp: dialog3.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) dialog3.h -o moc_dialog3.cpp

moc_alsettings.cpp: alsettings.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) alsettings.h -o moc_alsettings.cpp

moc_mdialog.cpp: mdialog.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) mdialog.h -o moc_mdialog.cpp

moc_tdialog.cpp: tdialog.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) tdialog.h -o moc_tdialog.cpp

moc_home.cpp: home.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/moc $(DEFINES) $(INCPATH) home.h -o moc_home.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_alarmlist.h ui_newalarm.h ui_dialog.h ui_dialog2.h ui_world.h ui_dialog3.h ui_alsettings.h ui_mdialog.h ui_tdialog.h ui_home.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_alarmlist.h ui_newalarm.h ui_dialog.h ui_dialog2.h ui_world.h ui_dialog3.h ui_alsettings.h ui_mdialog.h ui_tdialog.h ui_home.h
ui_mainwindow.h: mainwindow.ui \
		alarmbutton.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_alarmlist.h: alarmlist.ui
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/uic alarmlist.ui -o ui_alarmlist.h

ui_newalarm.h: newalarm.ui \
		valuebutton.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/uic newalarm.ui -o ui_newalarm.h

ui_dialog.h: dialog.ui
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/uic dialog.ui -o ui_dialog.h

ui_dialog2.h: dialog2.ui
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/uic dialog2.ui -o ui_dialog2.h

ui_world.h: world.ui
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/uic world.ui -o ui_world.h

ui_dialog3.h: dialog3.ui
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/uic dialog3.ui -o ui_dialog3.h

ui_alsettings.h: alsettings.ui \
		valuebutton.h
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/uic alsettings.ui -o ui_alsettings.h

ui_mdialog.h: mdialog.ui
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/uic mdialog.ui -o ui_mdialog.h

ui_tdialog.h: tdialog.ui
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/uic tdialog.ui -o ui_tdialog.h

ui_home.h: home.ui
	/home/matias/NokiaQtSDK/Maemo/4.6.2/targets/fremantle-pr13/bin/uic home.ui -o ui_home.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		alarmlist.h \
		world.h \
		osso-intl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp qmaemo5rotator.h \
		mainwindow.h \
		alarmlist.h \
		world.h \
		ui_mainwindow.h \
		alarmbutton.h \
		osso-intl.h \
		newalarm.h \
		maintdelegate.h \
		alsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

alarmlist.o: alarmlist.cpp qmaemo5rotator.h \
		alarmlist.h \
		ui_alarmlist.h \
		filedelegate.h \
		newalarm.h \
		osso-intl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alarmlist.o alarmlist.cpp

filedelegate.o: filedelegate.cpp osso-intl.h \
		filedelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filedelegate.o filedelegate.cpp

newalarm.o: newalarm.cpp qmaemo5rotator.h \
		newalarm.h \
		ui_newalarm.h \
		valuebutton.h \
		osso-intl.h \
		dialog.h \
		dialog2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newalarm.o newalarm.cpp

dialog.o: dialog.cpp qmaemo5rotator.h \
		dialog.h \
		ui_dialog.h \
		osso-intl.h \
		checkdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

checkdelegate.o: checkdelegate.cpp checkdelegate.h \
		osso-intl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o checkdelegate.o checkdelegate.cpp

valuebutton.o: valuebutton.cpp valuebutton.h \
		osso-intl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o valuebutton.o valuebutton.cpp

dialog2.o: dialog2.cpp qmaemo5rotator.h \
		dialog2.h \
		ui_dialog2.h \
		osso-intl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog2.o dialog2.cpp

alarmbutton.o: alarmbutton.cpp alarmbutton.h \
		osso-intl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alarmbutton.o alarmbutton.cpp

maintdelegate.o: maintdelegate.cpp maintdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maintdelegate.o maintdelegate.cpp

world.o: world.cpp qmaemo5rotator.h \
		world.h \
		ui_world.h \
		osso-intl.h \
		dialog3.h \
		filedelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o world.o world.cpp

dialog3.o: dialog3.cpp dialog3.h \
		ui_dialog3.h \
		osso-intl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog3.o dialog3.cpp

alsettings.o: alsettings.cpp qmaemo5rotator.h \
		alsettings.h \
		ui_alsettings.h \
		valuebutton.h \
		osso-intl.h \
		mdialog.h \
		tdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alsettings.o alsettings.cpp

mdialog.o: mdialog.cpp mdialog.h \
		ui_mdialog.h \
		osso-intl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mdialog.o mdialog.cpp

tdialog.o: tdialog.cpp qmaemo5rotator.h \
		tdialog.h \
		ui_tdialog.h \
		osso-intl.h \
		valuebutton.h \
		home.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tdialog.o tdialog.cpp

home.o: home.cpp home.h \
		ui_home.h \
		qmaemo5rotator.h \
		osso-intl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o home.o home.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_alarmlist.o: moc_alarmlist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_alarmlist.o moc_alarmlist.cpp

moc_filedelegate.o: moc_filedelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filedelegate.o moc_filedelegate.cpp

moc_newalarm.o: moc_newalarm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newalarm.o moc_newalarm.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_checkdelegate.o: moc_checkdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_checkdelegate.o moc_checkdelegate.cpp

moc_valuebutton.o: moc_valuebutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_valuebutton.o moc_valuebutton.cpp

moc_dialog2.o: moc_dialog2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog2.o moc_dialog2.cpp

moc_alarmbutton.o: moc_alarmbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_alarmbutton.o moc_alarmbutton.cpp

moc_world.o: moc_world.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_world.o moc_world.cpp

moc_dialog3.o: moc_dialog3.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog3.o moc_dialog3.cpp

moc_alsettings.o: moc_alsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_alsettings.o moc_alsettings.cpp

moc_mdialog.o: moc_mdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mdialog.o moc_mdialog.cpp

moc_tdialog.o: moc_tdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tdialog.o moc_tdialog.cpp

moc_home.o: moc_home.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_home.o moc_home.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

